[package]
name = "sonicbot"
version = "0.1.0"
authors = ["Westly Ward <sonicrules1234@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.19.1"
webpki = "0.21"
webpki-roots = "0.21.0"
acid-store = "0.6.0"
serde = "1.0.126"
serde_json = "1.0.64"
